# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# New Section
"""



# Com o Caps ativa e desativa porem tem que mirar

function OnEvent(event, arg)

    if event == "PROFILE_ACTIVATED" then
        EnablePrimaryMouseButtonEvents(true)
    end

    if event == "MOUSE_BUTTON_PRESSED" and arg == 1 then
        if IsKeyLockOn("capslock") and IsMouseButtonPressed(3) then
            repeat
                MoveMouseRelative(0, 2) -- DESCE a mira
                Sleep(1)
            until not IsMouseButtonPressed(1)
        end
    end
end


# Mirando ou atirando esta sempre ativo
function OnEvent(event, arg)

    if event == "PROFILE_ACTIVATED" then
        EnablePrimaryMouseButtonEvents(true)
    end

    if event == "MOUSE_BUTTON_PRESSED" and arg == 1 then
        repeat
            if IsMouseButtonPressed(3) then
                MoveMouseRelative(0, 2) -- mirando
            else
                MoveMouseRelative(0, 1) -- hipfire
            end
            Sleep(1)
        until not IsMouseButtonPressed(1)
    end
end